# Generated by Django 3.2.16 on 2024-12-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_auto_20241207_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=20, verbose_name='Тег'),
        ),
    ]
